/*==============================================================================
MIT License

Copyright (c) 2021 MaybeELEMENT

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Github: https://github.com/MaybeELEMENT/lexertk
==============================================================================*/
#ifndef LEXER_KIT_HPP
#define LEXER_KIT_HPP
#pragma once
#include <iostream>
#include <string>
#include <vector>
#include <stdio.h>
#include <map>
#include <algorithm>
#include <fstream>
namespace ELEMENT
{
    enum TOKENS {
        END_LINE  , STRING    , CHARACTER ,
        INTERGER  , DECIMAL   , KEYWORD   ,
        OPERATOR  , VARIABLE  , INCREMENT ,
        DECREMENT , PUNCTUATOR, COMPARISON,
        ASSIGNMENT, OR        , AND       ,
        BITWISE   , BOOLEAN   , TAB
    }eTokens;
    class Data
    {
    private:
        std::vector<std::pair<TOKENS, std::string>> tokens;
    public:
        void append(TOKENS token, std::string second) {tokens.push_back(make_pair(token, second));}
        size_t size() const { return tokens.size(); }
        std::string getType(int i) const {switch(i){
                case END_LINE: return "END_LINE";
                case STRING: return "STRING";
                case CHARACTER: return "CHARACTER";
                case INTERGER: return "INTERGER";
                case DECIMAL: return "DECIMAL";
                case KEYWORD: return "KEYWORD";
                case OPERATOR: return "OPERATOR";
                case VARIABLE: return "VARIABLE";
                case INCREMENT: return "INCREMENT";
                case DECREMENT: return "DECREMENT";
                case PUNCTUATOR: return "PUNCTUATOR";
                case COMPARISON: return "COMPARISON";
                case ASSIGNMENT: return "ASSIGNMENT";
                case OR: return "OR";
                case AND: return "AND";
                case BITWISE: return "BITWISE";
                case BOOLEAN: return "BOOLEAN";
                case TAB: return "TAB";
            }return "NULL";}
        std::string operator[](int i) const
        {
            return tokens[i].second;
        }
        std::string second(int i) const
        {
            return tokens[i].second;
        }
        TOKENS first(int i) const
        {
            return tokens[i].first;
        }
        std::string jsonlize() const
        {
            std::string res;
            res.append("[\n");
            for(int i = 0; i < tokens.size(); i++)
            {
                res.append("\t{\n\t\t\"" + getType(tokens[i].first) + "\": \"" + tokens[i].second + "\"\n\t},\n");
            }
            res.pop_back();
            res.pop_back();
            res.append("\n]");
            return res;
        }
        std::string yamlize() const
        {
            std::string res;
            res.append("#Generated by `ELEMENT's lexerKit`\n");
            res.append("lexer:\n");
            for(int i = 0; i < tokens.size(); i++)
            {
                res.append("\t- " + getType(tokens[i].first) + ":\n");
                res.append("\t\t- '" + tokens[i].second + "'\n");
            }
            res.pop_back();
            return res;
        }
        std::string xmlize() const
        {
            std::string res;
            res.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
            res.append("<!--Generated by `ELEMENT's lexerKit`-->\n");
            res.append("<lexer>\n");
            for(int i = 0; i < tokens.size(); i++)
            {
                std::string first = getType(tokens[i].first);
                std::for_each(first.begin(), first.end(), [](char & c) {
                    c = ::tolower(c);
                });
                std::string second = tokens[i].second;
                std::for_each(second.begin(), second.end(), [](char & c) {
                    c = ::tolower(c);
                });
                res.append("\t<" + first + ">" + second + "</" + first + ">\n");
            }
            res.append("</lexer>");
            return res;
        }
    };
    class Lexer
    {
    private:
        std::string val;
        std::string
        replaceAll(std::string original, std::string from, std::string to ) const
        {
            std::string results;
            std::string::const_iterator end = original.end();
            std::string::const_iterator current = original.begin();
            std::string::const_iterator next = std::search( current, end, from.begin(), from.end() );
            while ( next != end ) {
                results.append( current, next );
                results.append( to );
                current = next + from.size();
                next = std::search( current, end, from.begin(), from.end() );
            }
            results.append( current, next );
            return results;
        }
        void error(std::string value, std::string prefix, int line = 1) const
        {
            std::cout << replaceAll(prefix, "$line", std::to_string(line)) << value << std::endl;
            exit(1);
        }
        /*DEFINATION*/
        bool instr1 = false;
        bool escaped = false;
        bool instr2 = false;
        bool instring = false;
        bool wasstring = false;
        bool inchar = false;
        bool waschar = false;
        bool invar = false;
        bool wasint = false;
        bool inint = false;
        bool indecimal = false;
        /*DEFINATION*/
        void addRes(std::string temp, Data& res) const
        {
            if(temp.length() < 1);
            else if(wasstring) res.append(STRING, temp);
            else if(waschar) res.append(CHARACTER, temp);
            else if(use_boolean && temp == true_template) res.append(BOOLEAN, true_template);
            else if(use_boolean && temp == false_template) res.append(BOOLEAN, false_template);
            else if(use_and_or_keyword && temp == and_template) res.append(AND, and_template);
            else if(use_and_or_keyword && temp == or_template) res.append(OR, or_template);
            else if(inint) res.append(INTERGER, temp);
            else if(indecimal) res.append(DECIMAL, temp);
            else if(invar) res.append(VARIABLE, temp);
            else res.append(KEYWORD, temp);
        }
    public:
        static std::string read_file(std::string value)
        {
            std::ifstream file(value);
            if(file.is_open())
            {
                std::string str((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
                return str;
            }
            return "null";
        }
        /*CONFIGURATION*/
        std::string error_prefix = "Error on line $line : ";
        std::string decimal_error_msg = "Invalid syntax '.'";
        std::string unclose_string_1 = "Unclosed `'`";
        std::string unclose_string_2 = "Unclosed `\"`";
        std::string unfinished_escape = "Unfinished `\\`";
        std::string true_template = "true";
        std::string and_template = "and";
        std::string or_template = "or";
        std::string false_template = "false";
        bool str_classify = false;
        bool ignore_endline = false;
        bool remove_endline = false;
        bool str_error = true;
        bool decimal_error = true;
        int tab_length = 4;
        bool str_only_escape = false;
        bool use_and_or_on_operator = false;
        bool use_bitwise = false;
        bool use_boolean = true;
        bool use_and_or_keyword = false;
        /*CONFIGURATION*/
        Lexer(std::string value) : val(value)
        {
            val = value;
        }
        void Update(std::string value)
        {
            val = value;
        }
        Data Process()
        {
            int line = 1;
            std::string temp;
            Data res;
            for(int i = 0; i < val.length(); i++)
            {
                switch(val[i]){
                    case '\n':
                        if(instring || inchar);
                        else
                        {
                            if(!ignore_endline || !remove_endline)
                                addRes(temp, res);
                            if(!remove_endline)
                                res.append(END_LINE, "\\n");
                            temp.clear();
                            wasstring = false;
                            invar = false;
                            waschar = false;
                            inint = false;
                            escaped = false;
                            indecimal = false;
                        }
                        line++;
                    break;
                    case '\t':
                        if(instring || inchar) temp.push_back('\t');
                        else
                        {
                            res.append(TAB, "\\t");
                            addRes(temp, res);
                            temp.clear();
                            wasstring = false;
                            waschar = false;
                            invar = false;
                            inint = false;
                            escaped = false;
                            indecimal = false;
                        }
                    break;
                    case ' ':
                        if(instring || inchar) temp.push_back(' ');
                        else
                        {
                            bool istab = true;
                            for(int b = 0; b < tab_length; b++)
                            {
                                if(val[i + b] != ' ') istab = false;
                            }
                            if(istab) 
                            {
                                i += (tab_length - 1);
                                res.append(TAB, "\\t");
                            }
                            addRes(temp, res);
                            temp.clear();
                            wasstring = false;
                            waschar = false;
                            invar = false;
                            inint = false;
                            escaped = false;
                            indecimal = false;
                        }
                    break;
                    case '0':
                    case '1':
                    case '2':
                    case '3':
                    case '4':
                    case '5':
                    case '6':
                    case '7':
                    case '8':
                    case '9':
                        if(instring || inchar) temp.push_back(val[i]);
                        else
                        {
                            if(inint || indecimal)
                            {
                                temp.push_back(val[i]);
                            }
                            else if(temp.find_first_of("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_") == std::string::npos)
                            {
                                inint = true;
                                temp.push_back(val[i]);
                            }
                            else temp.push_back(val[i]);
                            escaped = false;
                        }
                    break;
                    case '.':
                        if(!instring && !inchar)
                        {
                            if(inint)
                            {
                                temp.append(".");
                                inint = false;
                            escaped = false;
                                indecimal = true;
                            }
                            else if(indecimal && decimal_error) error(decimal_error_msg, error_prefix, line);
                            else 
                            {
                                addRes(temp, res);
                                wasstring = false;
                                invar = false;
                                waschar = false;
                                inint = false;
                            escaped = false;
                                indecimal = false;
                                temp.clear();
                                res.append(OPERATOR, ".");
                            }
                        }
                        else temp.append(".");
                    break;
                    case '=':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '=')
                        {
                            res.append(COMPARISON, "==");
                            i++;
                        }
                        else res.append(OPERATOR, "=");
                    }
                    break;
                    case '!':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '=')
                        {
                            res.append(COMPARISON, "!=");
                            i++;
                        }
                        else res.append(OPERATOR, "!");
                    }
                    break;
                    case '&':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                        escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '&')
                        {
                            if(use_and_or_on_operator) res.append(AND, "&&");
                            else res.append(OPERATOR, "&&");
                            i++;
                        }
                        else if(val[i + 1] == '=')
                        {
                            res.append(ASSIGNMENT, "&=");
                            i++;
                        }
                        else if(use_bitwise) res.append(BITWISE, "&");
                        else res.append(OPERATOR, "&");
                    }
                    break;
                    case ':':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                        escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == ':')
                        {
                            res.append(OPERATOR, "::");
                            i++;
                        }
                        else if(val[i + 1] == '=')
                        {
                            res.append(ASSIGNMENT, ":=");
                            i++;
                        }
                        else res.append(OPERATOR, ":");
                    }
                    break;
                    case '?':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == ':')
                        {
                            res.append(OPERATOR, "?:");
                            i++;
                        }
                        else res.append(OPERATOR, "?");
                    }
                    break;
                    case '|':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '|')
                        {
                            if(use_and_or_on_operator) res.append(OR, "||");
                            else res.append(OPERATOR, "||");
                            i++;
                        }
                        else if(val[i + 1] == '=')
                        {
                            res.append(ASSIGNMENT, "|=");
                            i++;
                        }
                        else if(use_bitwise) res.append(BITWISE, "|");
                        else res.append(OPERATOR, "|");
                    }
                    break;
                    case '(':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        res.append(OPERATOR, "(");
                    }
                    break;
                    case ')':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        res.append(OPERATOR, ")");
                    }
                    break;
                    case '[':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        res.append(OPERATOR, "[");
                    }
                    break;
                    case ']':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        res.append(OPERATOR, "]");
                    }
                    break;
                    case '{':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        res.append(OPERATOR, "{");
                    }
                    break;
                    case '}':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        res.append(OPERATOR, "}");
                    }
                    break;
                    case '<':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '=')
                        {
                            res.append(COMPARISON, "<=");
                            i++;
                        }
                        else if(val[i + 1] == '<')
                        {
                            res.append(OPERATOR, "<<");
                            i++;
                        }
                        else if(val[i + 1] == '<' && val[i + 2] == '=')
                        {
                            res.append(ASSIGNMENT, "<<=");
                            i += 2;
                        }
                        else if(val[i + 1] == '=' && val[i + 2] == '>')
                        {
                            res.append(OPERATOR, "<=>");
                            i += 2;
                        }
                        else res.append(COMPARISON, "<");
                    }
                    break;
                    case '>':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '=')
                        {
                            res.append(COMPARISON, ">=");
                            i++;
                        }
                        else if(val[i + 1] == '>')
                        {
                            res.append(OPERATOR, ">>");
                            i++;
                        }
                        else if(val[i + 1] == '>' && val[i + 2] == '=')
                        {
                            res.append(ASSIGNMENT, ">>=");
                            i += 2;
                        }
                        else res.append(COMPARISON, ">");
                    }
                    break;
                    case ';':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        res.append(PUNCTUATOR, ";");
                    }
                    break;
                    case '+':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '+')
                        {
                            res.append(INCREMENT, "++");
                            i++;
                        }
                        else if(val[i + 1] == '=')
                        {
                            res.append(ASSIGNMENT, "+=");
                            i++;
                        }
                        else res.append(OPERATOR, "+");
                    }
                    break;
                    case '^':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '=')
                        {
                            res.append(ASSIGNMENT, "^=");
                            i++;
                        }
                        else if(use_bitwise) res.append(BITWISE, "^");
                        else res.append(OPERATOR, "^");
                    }
                    break;
                    case '~':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(use_bitwise) res.append(BITWISE, "~");
                        else res.append(OPERATOR, "~");
                    }
                    break;
                    case '-':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '-')
                        {
                            res.append(DECREMENT, "--");
                            i++;
                        }
                        else if(val[i + 1] == '>')
                        {
                            res.append(OPERATOR, "->");
                            i++;
                        }
                        else if(val[i + 1] == '=')
                        {
                            res.append(ASSIGNMENT, "-=");
                            i++;
                        }
                        else res.append(OPERATOR, "-");
                    }
                    break;
                    case '*':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '=')
                        {
                            res.append(ASSIGNMENT, "*=");
                            i++;
                        }
                        else
                        res.append(OPERATOR, "*");
                    }
                    break;
                    case '/':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '=')
                        {
                            res.append(ASSIGNMENT, "/=");
                            i++;
                        }
                        else
                        res.append(OPERATOR, "/");
                    }
                    break;
                    case '%':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        if(val[i + 1] == '=')
                        {
                            res.append(ASSIGNMENT, "%=");
                            i++;
                        }
                        else
                        res.append(OPERATOR, "%");
                    }
                    break;
                    case ',':
                    if(inchar || instring) temp.push_back(val[i]);
                    else
                    {
                        addRes(temp, res);
                        wasstring = false;
                        invar = false;
                        waschar = false;
                        inint = false;
                            escaped = false;
                        indecimal = false;
                        temp.clear();
                        res.append(OPERATOR, ",");
                    }
                    break;
                    case '"':
                        if(inchar || instr1 || escaped) 
                        {
                            temp.push_back('"');
                            escaped = false;
                        }
                        else if(!instring)
                        {
                            instr2 = true;
                            instring = true;
                        }
                        else
                        {
                            instr2 = false;
                            instring = false;
                            wasstring = true;
                        }
                    break;
                    case '$':
                    if(instring || inchar) temp.push_back('$');
                    else invar = true;
                    break;
                    case '\'':
                        if(instr2 || escaped) 
                        {
                            temp.push_back('\'');
                            escaped = false;
                        }
                        else if(!instr1 && !inchar)
                        {
                            instr1 = true;
                            if(str_classify)
                            {
                                inchar = true;
                            }
                            else instring = true;
                        }
                        else
                        {
                            if(str_classify)
                            {
                                if(temp.length() > 1 && str_error) error("Multi-character character", error_prefix, line);
                            }
                            if(!str_classify) 
                            {instring = false;}
                            else inchar = false;
                            if(str_classify) waschar = true;
                            else wasstring = true;
                            instr1 = false;
                        }
                    break;
                    case '\\':
                    if(escaped) 
                    {
                        escaped = false;
                        temp.append("\\");
                    }
                    else escaped = true;
                    break;
                    default:
                    if(escaped)
                    {
                        if(str_only_escape)
                        {
                            if(instring || inchar)
                            {
                                if(val[i] == 'n') temp.push_back('\n');
                                else if(val[i] == 'r') temp.push_back('\r');
                                else if(val[i] == 't') temp.push_back('\t');
                                else if(val[i] == 'b') temp.push_back('\b');
                                else if(val[i] == 'f') temp.push_back('\f');
                                else if(val[i] == 'v') temp.push_back('\v');
                            }
                        }
                        else
                        {
                            if(val[i] == 'n') temp.push_back('\n');
                            else if(val[i] == 'r') temp.push_back('\r');
                            else if(val[i] == 't') temp.push_back('\t');
                            else if(val[i] == 'b') temp.push_back('\b');
                            else if(val[i] == 'f') temp.push_back('\f');
                            else if(val[i] == 'v') temp.push_back('\v');
                        }
                        escaped = false;
                    }
                    else
                        temp.push_back(val[i]);
                    break;
                }
            }
            addRes(temp, res);
            temp.clear();
            wasstring = false;
            waschar = false;
            inint = false;
            if(escaped) error(unfinished_escape, error_prefix, line);
            escaped = false;
            invar = false;
            indecimal = false;
            if(instr1 && str_error) error(unclose_string_1, error_prefix, line);
            if(instr2 && str_error) error(unclose_string_2, error_prefix, line);
            return res;
        }
    };
}
#endif
